#!/sbin/openrc-run
# Copyright 1999-2024
# Distributed under the terms of the GNU General Public License v2

description="Turing Smart Screen"

depend()
{
	keyword -docker
}

_turing-smart-screen()
{
	User="user"
	WorkingDirectory="/opt/turing-smart-screen-python/"
	[ -z "$1" ] && return 1
		python3 main.py
	return $retval
}

start()
{
	ebegin "Enabling turing-smart-screen"
	_turing-smart-screen +
	eend $? "Failed to enable turing-smart-screen"
}

stop()
{
	yesno $RC_GOINGDOWN && return 0

	ebegin "Disabling turing-smart-screen"
	_turing-smart-screen -
	eend $? "Failed to disable turing-smart-screen"
}

depend() {
	need net
	use avahi-daemon ypbind
}
